# Generated by Django 4.0.5 on 2022-07-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='product', verbose_name='Фотография')),
                ('color', models.CharField(max_length=155, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=155, verbose_name='')),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_tags', to='products.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=155, verbose_name='Ширина')),
                ('deep', models.CharField(max_length=155, verbose_name='Глубина')),
                ('heigth', models.CharField(max_length=155, verbose_name='Высота')),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_size', to='products.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('date', models.DateField()),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products', verbose_name='Фотография')),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='products.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='prod_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prodtype', verbose_name='Тип'),
        ),
    ]
