# Generated by Django 4.0.5 on 2022-07-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catalog_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='images',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.catalog'),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='price',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.catalog'),
        ),
        migrations.AlterField(
            model_name='size',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.catalog'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.catalog'),
        ),
    ]
