# Generated by Django 4.0.5 on 2022-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_catalog_img_alter_images_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, max_length=2, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
