# Generated by Django 4.0.5 on 2022-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_price_discount_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
