# Generated by Django 4.0.5 on 2022-07-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_furniture_furniturecategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'Заголовок советы', 'verbose_name_plural': 'Заголовки советы'},
        ),
        migrations.AlterModelOptions(
            name='econom',
            options={'verbose_name': 'Заголовок экономь', 'verbose_name_plural': 'Заголовки экономь'},
        ),
        migrations.AlterModelOptions(
            name='furniturecategories',
            options={'verbose_name': 'Фурнитур Категория', 'verbose_name_plural': 'Фурнитур Категории'},
        ),
    ]
