# Generated by Django 4.0.5 on 2022-07-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_advantages_options_alter_econom_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pluses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Плюс')),
                ('body', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='pluses', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Плюс компании',
                'verbose_name_plural': 'Плюсы компании',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Выгода')),
                ('body', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='pluses', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Выгода',
                'verbose_name_plural': 'Выгоды',
            },
        ),
    ]
